import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Lexend_Deca,
  DM_Serif_Display,
} from "next/font/google";
import "./globals.css";
import { Texture } from "@/components/texture";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lexantDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexantDeca.variable} ${dmSerifDisplay.variable} antialiased`}
      >
        {children}
        <Texture />
      </body>
    </html>
  );
}
